# Generated by Django 5.2.3 on 2025-07-25 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MotivationalTip",
        ),
    ]
